name: Run Tests
on: [push]
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: npm install
        run: npm install

      - name: npm test
        run: npm test
